run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - goimports
    - staticcheck
    - unused
    - typecheck
    - ineffassign
    - errcheck
linters-settings:
  staticcheck:
    checks:
      - all
